repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-yaml
    - repo: https://github.com/golangci/golangci-lint
      rev: v1.45.0
      hooks:
          - id: golangci-lint
            args: [--enable, gofmt]
